# Generated by Django 3.1.2 on 2020-10-10 15:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistem_url', models.CharField(max_length=100, verbose_name='url')),
                ('baslık', models.CharField(max_length=100, verbose_name='Başlık')),
                ('icerik', ckeditor.fields.RichTextField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim1')),
                ('image2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim2')),
                ('image3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim3')),
            ],
        ),
    ]
