# Generated by Django 3.1.2 on 2020-10-10 19:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_i̇letisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkında',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslık', models.CharField(max_length=100, verbose_name='Başlık')),
                ('icerik', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
