# Generated by Django 3.1.2 on 2020-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_hakkında'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='isim')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
            ],
        ),
        migrations.AddField(
            model_name='hakkında',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
