# Generated by Django 3.1.2 on 2020-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201012_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇letisim',
            name='harita',
            field=models.CharField(default=1, max_length=300, verbose_name='mail'),
            preserve_default=False,
        ),
    ]
