# Generated by Django 3.1.2 on 2020-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201012_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hakkında',
            name='image',
        ),
        migrations.AddField(
            model_name='hakkında',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim1'),
        ),
        migrations.AddField(
            model_name='hakkında',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim2'),
        ),
        migrations.AddField(
            model_name='hakkında',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim3'),
        ),
    ]
