# Generated by Django 3.1.2 on 2020-10-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201012_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anasayfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anabaşlık', models.CharField(max_length=100, verbose_name='anabaşlık')),
                ('altbaşlık', models.CharField(max_length=100, verbose_name='altbaşlık')),
                ('paragraf', models.CharField(max_length=100, verbose_name='paragraf')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
            ],
        ),
    ]
