# Generated by Django 3.1.2 on 2020-10-12 19:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_anasayfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anasayfa',
            name='paragraf',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
