# Generated by Django 3.1.2 on 2020-10-12 20:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201012_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100, verbose_name='başlık')),
                ('icerik', ckeditor.fields.RichTextField()),
                ('resim', models.FileField(blank=True, null=True, upload_to='', verbose_name='resim')),
                ('tür', models.CharField(choices=[(1, 'bitti'), (2, 'devam ediyor'), (3, 'anlaşıldı')], default=1, max_length=2)),
            ],
        ),
    ]
