# Generated by Django 3.1.2 on 2020-10-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_proje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='tür',
            field=models.CharField(choices=[('1', 'bitti'), ('2', 'devam ediyor'), ('3', 'anlaşıldı')], default=1, max_length=2),
        ),
    ]
