# Generated by Django 3.1.2 on 2020-10-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20201012_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazı', models.CharField(max_length=100, verbose_name='yazı')),
                ('resim', models.FileField(blank=True, null=True, upload_to='', verbose_name='resim')),
            ],
        ),
    ]
